const Pet = require('../models/Pet');

const petData = [
  {
    name: 'Buddy',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: 3,
    health_status: 'Healthy',
    description: 'Friendly and energetic.',
    location: 'New York, NY',
    user_id: 1,
  },
  {
    name: 'Bella',
    type: 'Dog',
    breed: 'Labrador Retriever',
    age: 2,
    health_status: 'Healthy',
    description: 'Loves to play fetch.',
    location: 'Los Angeles, CA',
    user_id: 2,
  },
  {
    name: 'Charlie',
    type: 'Dog',
    breed: 'Beagle',
    age: 4,
    health_status: 'Healthy',
    description: 'Loves to sniff around.',
    location: 'Chicago, IL',
    user_id: 3,
  },
  {
    name: 'Max',
    type: 'Dog',
    breed: 'German Shepherd',
    age: 5,
    health_status: 'Healthy',
    description: 'Very loyal and protective.',
    location: 'Houston, TX',
    user_id: 4,
  },
  {
    name: 'Lucy',
    type: 'Dog',
    breed: 'French Bulldog',
    age: 3,
    health_status: 'Healthy',
    description: 'Small but brave.',
    location: 'Phoenix, AZ',
    user_id: 5,
  },
  {
    name: 'Daisy',
    type: 'Dog',
    breed: 'Poodle',
    age: 2,
    health_status: 'Healthy',
    description: 'Very intelligent.',
    location: 'Philadelphia, PA',
    user_id: 1,
  },
  {
    name: 'Milo',
    type: 'Dog',
    breed: 'Pomeranian',
    age: 1,
    health_status: 'Healthy',
    description: 'Tiny and adorable.',
    location: 'San Antonio, TX',
    user_id: 2,
  },
  {
    name: 'Jack',
    type: 'Dog',
    breed: 'Rottweiler',
    age: 4,
    health_status: 'Healthy',
    description: 'Strong and confident.',
    location: 'San Diego, CA',
    user_id: 3,
  },
  {
    name: 'Oliver',
    type: 'Dog',
    breed: 'Yorkshire Terrier',
    age: 2,
    health_status: 'Healthy',
    description: 'Loves to be pampered.',
    location: 'Dallas, TX',
    user_id: 4,
  },
  {
    name: 'Rocky',
    type: 'Dog',
    breed: 'Boxer',
    age: 3,
    health_status: 'Healthy',
    description: 'Energetic and playful.',
    location: 'San Jose, CA',
    user_id: 5,
  },
  {
    name: 'Whiskers',
    type: 'Cat',
    breed: 'Siamese',
    age: 4,
    health_status: 'Healthy',
    description: 'Curious and playful.',
    location: 'New York, NY',
    user_id: 1,
  },
  {
    name: 'Mittens',
    type: 'Cat',
    breed: 'Persian',
    age: 3,
    health_status: 'Healthy',
    description: 'Loves to cuddle.',
    location: 'Los Angeles, CA',
    user_id: 2,
  },
  {
    name: 'Shadow',
    type: 'Cat',
    breed: 'Maine Coon',
    age: 5,
    health_status: 'Healthy',
    description: 'Large and gentle.',
    location: 'Chicago, IL',
    user_id: 3,
  },
  {
    name: 'Simba',
    type: 'Cat',
    breed: 'Bengal',
    age: 2,
    health_status: 'Healthy',
    description: 'Active and vocal.',
    location: 'Houston, TX',
    user_id: 4,
  },
  {
    name: 'Luna',
    type: 'Cat',
    breed: 'Russian Blue',
    age: 3,
    health_status: 'Healthy',
    description: 'Calm and affectionate.',
    location: 'Phoenix, AZ',
    user_id: 5,
  },
  {
    name: 'Bella',
    type: 'Cat',
    breed: 'Sphynx',
    age: 1,
    health_status: 'Healthy',
    description: 'Hairless and friendly.',
    location: 'Philadelphia, PA',
    user_id: 1,
  },
  {
    name: 'Kitty',
    type: 'Cat',
    breed: 'British Shorthair',
    age: 2,
    health_status: 'Healthy',
    description: 'Quiet and easy-going.',
    location: 'San Antonio, TX',
    user_id: 2,
  },
  {
    name: 'Nala',
    type: 'Cat',
    breed: 'Scottish Fold',
    age: 3,
    health_status: 'Healthy',
    description: 'Playful and affectionate.',
    location: 'San Diego, CA',
    user_id: 3,
  },
  {
    name: 'Ginger',
    type: 'Cat',
    breed: 'Abyssinian',
    age: 2,
    health_status: 'Healthy',
    description: 'Active and adventurous.',
    location: 'Dallas, TX',
    user_id: 4,
  },
  {
    name: 'Cleo',
    type: 'Cat',
    breed: 'Ragdoll',
    age: 4,
    health_status: 'Healthy',
    description: 'Loves to be held.',
    location: 'San Jose, CA',
    user_id: 5,
  },
];

const seedPets = () => Pet.bulkCreate(petData);

module.exports = seedPets;