const Pet = require('../models/Pet');

const petData = [
  {
    name: 'Buddy',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: 3,
    health_status: 'Healthy',
    description: 'Friendly and energetic.',
    location: 'New York, NY',
    user_id: 1,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Bella',
    type: 'Dog',
    breed: 'Labrador Retriever',
    age: 2,
    health_status: 'Healthy',
    description: 'Loves to play fetch.',
    location: 'Los Angeles, CA',
    user_id: 2,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Charlie',
    type: 'Dog',
    breed: 'Beagle',
    age: 4,
    health_status: 'Healthy',
    description: 'Loves to sniff around.',
    location: 'Chicago, IL',
    user_id: 3,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Max',
    type: 'Dog',
    breed: 'German Shepherd',
    age: 5,
    health_status: 'Healthy',
    description: 'Very loyal and protective.',
    location: 'Houston, TX',
    user_id: 4,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Lucy',
    type: 'Dog',
    breed: 'French Bulldog',
    age: 3,
    health_status: 'Healthy',
    description: 'Small but brave.',
    location: 'Phoenix, AZ',
    user_id: 5,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Whiskers',
    type: 'Cat',
    breed: 'Siamese',
    age: 4,
    health_status: 'Healthy',
    description: 'Curious and playful.',
    location: 'New York, NY',
    user_id: 1,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Mittens',
    type: 'Cat',
    breed: 'Persian',
    age: 3,
    health_status: 'Healthy',
    description: 'Loves to cuddle.',
    location: 'Los Angeles, CA',
    user_id: 2,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Shadow',
    type: 'Cat',
    breed: 'Maine Coon',
    age: 5,
    health_status: 'Healthy',
    description: 'Large and gentle.',
    location: 'Chicago, IL',
    user_id: 3,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Simba',
    type: 'Cat',
    breed: 'Bengal',
    age: 2,
    health_status: 'Healthy',
    description: 'Active and vocal.',
    location: 'Houston, TX',
    user_id: 4,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
  {
    name: 'Luna',
    type: 'Cat',
    breed: 'Russian Blue',
    age: 3,
    health_status: 'Healthy',
    description: 'Calm and affectionate.',
    location: 'Phoenix, AZ',
    user_id: 5,
    image_url: 'https://infolific.com/images/dogs/dog-with-lost-sign-around-neck.jpg',
  },
];

const seedPets = async () => {
  await Pet.bulkCreate(petData);
};

module.exports = seedPets;

